cfg/config.go
cfg/default.go
launcher.go

Remove godog configuration from golium configuration struct. It can be configured by flags.

feat: remove godog configuration

---

steps/http/session.go
steps/http/steps.go
steps/redis/session.go
steps/redis/steps.go
test/acceptance/features/http.feature
test/acceptance/features/redis.feature

- Add configuration for HTTP request Host value
- Add setting and validation functions for [Redis hash values][1]
- Refactor Redis Session `ValidateEmptyValue` using [Exists command][2]
[1]: https://www.tutorialspoint.com/redis/redis_hashes.htm
[2]: https://www.tutorialspoint.com/redis/keys_exists.htm

feat: improve http and redis steps

---

steps/dns/session.go
steps/dns/steps.go
test/acceptance/environments/local.yml
test/acceptance/features/dns.feature
value.go

1 - Implemented a configurable DNS response timeout
2 - Draft to avoid eDNS0 OPT record values as SHA256

feat: dns validations

---

steps/common/steps.go
test/acceptance/features/http.feature
value.go
value_test.go

- Support of composition of tags and fix multiple issues related to value tags.

fix: better support of value tags

---

steps/http/session.go
steps/http/steps.go
steps/jwt/session.go
steps/jwt/steps.go
test/acceptance/environments/local.yml
test/acceptance/features/common.feature
test/acceptance/features/http.feature
test/acceptance/features/jwt.feature
value.go

- New step to send a x-www-form-urlencoded HTTP request.
- New step to configure basic authentication in HTTP request.
- New value tag: `BASE64`

feat: support urlencoded http requests

---

steps/redis/steps.go
test/acceptance/features/redis.feature

Resolved the missing parameters convertion for some redis steps

fix: context parameter conversions in redis steps

---

steps/rabbit/logger.go
steps/rabbit/session.go

Added log for RabbitMQ subcription event

chore: Add log for RabbitMQ subcription event

---

steps/common/steps.go
value.go

Change UUID generation method by a more unpredictable approach

chore: Refactor UUID generation

---

test/acceptance/features/mockhttp.feature
value.go

Improve support for tags in json data.
For example with mock steps.

fix: improve support for nested value tags in json data

---

steps/http/session.go
steps/http/steps.go
steps/s3/session.go
steps/s3/steps.go
table.go
test/acceptance/environments/local.yml
test/acceptance/features/http.feature
test/acceptance/features/s3.feature

A step is added to check that given headers are NOT received. 
It is necessary to add a new function to parse tables with a single column.

feat: new step into http feature

---

steps/rabbit/session.go
steps/rabbit/steps.go
test/acceptance/features/rabbit.feature

Two new steps are added:
1.  I wait up to "X" seconds for "Y" rabbit messages with the standard properties
2.  the body of the rabbit message in position "N" has the JSON properties

feat: rabbitmq to check n messages with std props and json bodies

---

steps/common/steps.go
steps/s3/session.go
test/acceptance/environments/local.yml

Fix regexp to lookup IP from Hostname

bug: Fix regexp to lookup IP from Hostname

---

steps/common/steps.go
test/acceptance/environments/local.yml
test/acceptance/features/common.feature

Allow parameters in delay steps

feat: Allow parameters in delay steps

---

steps/dns/session.go
steps/dns/steps.go
test/acceptance/features/doh.feature

Implement query parameters as  new step in DoH functionality

chore: [DoH] Implement query parameters as step

---

steps/http/json.go
steps/http/session.go
steps/http/steps.go
test/acceptance/features/http.feature

- GetParamFromJSON to public
- ValidateResponseFromJSONFile should evaluate full reponse body or specified parameter

fix: [HTTP] add some fixes to http steps

---

.github/pull_request_template.md

chore: test pr template usage

---

steps/dns/session.go
steps/dns/steps.go
steps/http/session.go
steps/http/steps.go
steps/jwt/session.go
steps/jwt/steps.go
steps/rabbit/session.go
steps/rabbit/steps.go
steps/redis/session.go
steps/redis/steps.go

Remove return error signature on setters from sessions structs #64 
closes #64

#64 feat: remove return error signature on setters from sessions structs

---

.github/workflows/lint.yml
.golangci.yml
README.md
sonar-project.properties

Configure static analysis in project
Static analysis configuration using golangci-lint and sonarcloud

chore: static analysis

---

README.md

Update quality gate badge link:
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=golium&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=golium)

chore: update quality gate badge

---

.github/workflows/sonarcloud.yml
.golangci.yml

Configure incremental analysis on pull request using golangci-lint to export in sonarcloud

chore: configure incremental analysis on pr

---

steps/dns/record.go
steps/dns/record_test.go
steps/dns/session.go
steps/dns/session_test.go
steps/dns/steps.go

Fix sonar bugs and add unit tests related to DNS module

fix magnet-7803: fix dns sonar bugs

---

.golangci.yml
steps/jwt/jwt.go
steps/jwt/session.go
steps/jwt/session_test.go

fix(MAGNETO-7806): Fixed jwt sonar issues

---

sonar-project.properties

Chore: update test coverage exclusions with logger and steps files

chore: update tests coverage exclusions

---

sonar-project.properties
steps/elasticsearch/client.go
steps/elasticsearch/client_mock.go
steps/elasticsearch/context.go
steps/elasticsearch/model.go
steps/elasticsearch/session.go
steps/elasticsearch/session_test.go
steps/elasticsearch/steps.go

fix(MAGNETO-7804): elasticsearch sonar bugs

---

steps/http/session.go
steps/redis/logger.go

fix: Missed redis logger and http session issues

---

mock/http/steps.go
sonar-project.properties

fix: http mock sonar issues

---

config.go
config_test.go

fix: config sonar issues

---

steps/s3/client.go
steps/s3/client_mock.go
steps/s3/context.go
steps/s3/session.go
steps/s3/session_test.go
steps/s3/steps.go

fix(MAGNETO-7809): s3 sonar issues

---

cmd/mockhttp/main.go
test/acceptance/golium_test.go
test/acceptance/steps/aggregated/context.go
test/acceptance/steps/aggregated/session.go

fix: test acceptance sonar issues

---

util_test.go

Add unitest util.go

---

value.go
value_test.go

fix: value sonar issues

---

value.go

fix: lll linter issue

---

steps/rabbit/session.go
steps/rabbit/session_test.go
steps/rabbit/steps.go

fix: Fixed rabbitmq wait for messages

---

steps/http/session.go

fix: http validation error to be in response body

---

steps/http/schema/adapters.go
steps/http/schema/adapters_test.go
steps/http/session.go
steps/http/session_test.go
steps/http/steps.go

Fix new http steps to get endpoint from configuration
Not needed
Unit and acceptance test

fix: add missing endpoint from configuration

---

.github/workflows/sonarcloud.yml
.gitignore
sonar-project.properties

Chore: Include unit test report counter in sonarqube

chore: test report counter into sonarqube

---

steps/http/model/request.go
steps/http/model/request_test.go
steps/http/schema/adapters.go
steps/http/schema/adapters_test.go
steps/http/session.go
steps/http/session_test.go
steps/http/steps.go
test/acceptance/environments/ci.yml
test/acceptance/environments/local.yml
test/acceptance/features/http/request.feature
test/acceptance/golium_test.go
test/acceptance/test_data/test.txt

Add support for HTTP requests with multipart format, adding files and form fields.
Added unit and acceptance tests for the new steps.

feat(QAB-207): add http request multipart support

---

mock/http/requests.go
steps/aws/s3/session.go
test/acceptance/features/mockhttp.feature

chore: add multiending path to mock

---

test/acceptance/environments/ci.yml
test/acceptance/environments/local.yml
test/acceptance/features/http/http.feature

- Fix local environment configuration

5609 fix: [GOLIUM] Tests for http fail in the local environment
